# Generated by Django 5.2.6 on 2025-09-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='current_usage_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
