# Generated by Django 5.2.6 on 2025-09-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
