# Generated by Django 5.2.6 on 2025-09-26 19:28

import apps.storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_file_file_path_file_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.storage.models.user_directory_path),
        ),
    ]
