# Generated by Django 5.2.6 on 2025-09-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_file_file_path_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='last_downloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
